version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: mi_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: doriax
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  cache:
    driver: local
  postgres_data:
    driver: local
